### ISSUE TITLE
Delete Unused Framework

### ISSUE THREAD

**Issue by Tsugami** [Simplicity/Simplicity#8]
- [x] - weather
- [x] - urban
- [x] - node-google-translate-skidz
- [x] - colors
- [ ] - moment
- [ ] - moment-duration-format

**Comment by Tsugami** [comment]
https://youtu.be/P7AONrmOvKk

**Comment by Almeeida** [comment]
remover os modulos?

**Comment by Tsugami** [comment]
esses wrappers os pode fazer manualmente

**Comment by Tsugami** [comment]
eles tem muitas funções desnecessárias pro bot

**Comment by Almeeida** [comment]
hm ok

**Comment by Almeeida** [comment]
moment eu não sei
